<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CLA_Administration_Web</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;8618;8603;024;8600;8602;8604</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;8618;8603;024;8600;8602;8604</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Views\Settings\SkinsOfflineImage\" />
    <Folder Include="Views\Settings\TargetGroup\" />
    <Folder Include="Views\Shared\Components\Custom\Modules\Views\" />
    <Folder Include="Views\Shared\Components\Custom\Settings\TargetGroupModal\" />
    <Folder Include="wwwroot\assets\plugins\bootstrap-material-datetimepicker\css\" />
    <Folder Include="wwwroot\resources\reports\policy\" />
    <Folder Include="wwwroot\resources\reports\survey\" />
    <Folder Include="wwwroot\resources\reports\ticker\" />
    <Folder Include="wwwroot\scripts\ts\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.10" />
    <PackageReference Include="Microsoft.CodeAnalysis" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="4.11.0" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.6.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="ReportViewerCore.NETCore" Version="15.1.23" />
    <PackageReference Include="System.Diagnostics.EventLog" Version="6.0.0" />
    <PackageReference Include="System.IO.Packaging" Version="8.0.1" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="7.0.2" />
    <PackageReference Include="System.Security.Permissions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
      <AvailableItemName Include="TypeScriptCompile" />
  </ItemGroup>
  <ItemGroup>
      <TypeScriptCompile Include="$(ProjectDir)\**\*.ts" />
  </ItemGroup>
  <Target Name="BeforeBuild">
      <Exec Command="&quot;$(PROGRAMFILES)\Microsoft SDKs\TypeScript\0.8.0.0\tsc&quot; -target ES5 @(TypeScriptCompile ->'&quot;%(fullpath)&quot;', ' ')" IgnoreExitCode="true" />
  </Target>
  <ItemGroup>
    <TypeScriptCompile Remove="node_modules\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="Views\Settings\DefaultFonts.cshtml" />
    <Content Remove="wwwroot\js\reports\piechart.js" />
  </ItemGroup>
  <ItemGroup>
    <_ContentIncludedByDefault Remove="Views\Settings\DefaultFonts.cshtml" />
    <_ContentIncludedByDefault Remove="wwwroot\js\reports\piechart.js" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Views\Settings\DefaultFonts.cshtml" />
    <None Include="wwwroot\js\reports\piechart.js" />
    <None Include="wwwroot\resources\reports\rptActiveUsers.rdlc" />
    <None Include="wwwroot\resources\reports\rptActiveMachines.rdlc" />
    <None Include="wwwroot\resources\reports\rptDispatch_Listings.rdlc" />
    <None Include="wwwroot\resources\reports\rptPolicy_All.rdlc" />
    <None Include="wwwroot\resources\reports\rptPolicy_Completed_Responses.rdlc" />
    <None Include="wwwroot\resources\reports\rptPolicy_DataOnly.rdlc" />
    <None Include="wwwroot\resources\reports\rptPolicy_Outstanding.rdlc" />
    <None Include="wwwroot\resources\reports\rptPolicy_Questions_Detail.rdlc" />
    <None Include="wwwroot\resources\reports\rptPolicy_Response_Summary.rdlc" />
    <None Include="wwwroot\resources\reports\rptReporting_STM_All_Export_Only.rdlc" />
    <None Include="wwwroot\resources\reports\rptReporting_STM_Export_Only.rdlc" />
    <None Include="wwwroot\resources\reports\rptReporting_Surveys_Export_Only.rdlc" />
    <None Include="wwwroot\resources\reports\rptReporting_Survey_All_Export_Only.rdlc" />
    <None Include="wwwroot\resources\reports\rptReporting_Ticker_All_Export_Only.rdlc" />
    <None Include="wwwroot\resources\reports\rptReporting_Ticker_Export_Only.rdlc" />
    <None Include="wwwroot\resources\reports\rptSTM_All.rdlc" />
    <None Include="wwwroot\resources\reports\rptSTM_Outstanding_Summary.rdlc" />
    <None Include="wwwroot\resources\reports\rptSTM_Question_Summary.rdlc" />
    <None Include="wwwroot\resources\reports\rptSTM_Responses_Breakdown.rdlc" />
    <None Include="wwwroot\resources\reports\rptSTM_Summary.rdlc" />
    <None Include="wwwroot\resources\reports\rptSurvey_All.rdlc" />
    <None Include="wwwroot\resources\reports\rptSurvey_Complete_Opt_Out.rdlc" />
    <None Include="wwwroot\resources\reports\rptSurvey_Comprehensive.rdlc" />
    <None Include="wwwroot\resources\reports\rptSurvey_No_Response_Detail.rdlc" />
    <None Include="wwwroot\resources\reports\rptSurvey_Opt_In_No_Response.rdlc" />
    <None Include="wwwroot\resources\reports\rptSurvey_Opt_Out.rdlc" />
    <None Include="wwwroot\resources\reports\rptSurvey_Outstanding.rdlc" />
    <None Include="wwwroot\resources\reports\rptSurvey_Questions_Detail.rdlc" />
    <None Include="wwwroot\resources\reports\rptSurvey_Questions_Detail_Correct.rdlc" />
    <None Include="wwwroot\resources\reports\rptSurvey_Questions_Detail_Incorrect.rdlc" />
    <None Include="wwwroot\resources\reports\rptSurvey_Questions_Detail_Opt_In.rdlc" />
    <None Include="wwwroot\resources\reports\rptSurvey_Questions_Detail_Opt_In_Correct.rdlc" />
    <None Include="wwwroot\resources\reports\rptSurvey_Questions_Detail_Opt_In_Incorrect.rdlc" />
    <None Include="wwwroot\resources\reports\rptSurvey_Questions_Summary.rdlc" />
    <None Include="wwwroot\resources\reports\rptSurvey_Questions_Summary_Opt_In.rdlc" />
    <None Include="wwwroot\resources\reports\rptSurvey_Summary.rdlc" />
    <None Include="wwwroot\resources\reports\rptTicker_All.rdlc" />
    <None Include="wwwroot\resources\reports\rptTicker_Completed.rdlc" />
    <None Include="wwwroot\resources\reports\rptTicker_Outstanding.rdlc" />
    <None Include="wwwroot\resources\reports\rptTicker_Summary.rdlc" />
    <None Include="wwwroot\resources\reports\rtpSTM_Outstanding.rdlc" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Views\Shared\Components\Custom\Form\DataTable.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="Views\Shared\Helpers\HtmlHelpers\AppUrlsHelper.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

    <ItemGroup>
        <Reference Include="CLACommonFunctionsLibrary_NET">
            <HintPath>dlls\CLACommonFunctionsLibrary_NET.dll</HintPath>
        </Reference>
    </ItemGroup>
    <ItemGroup>
        <Reference Include="CLAModulesLibrary">
            <HintPath>dlls\CLAModulesLibrary.dll</HintPath>
        </Reference>
    </ItemGroup>
    <ItemGroup>
      <UpToDateCheckInput Remove="Views\Settings\DefaultFonts.cshtml" />
    </ItemGroup>
    
</Project>
