<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CLA_Administration_Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="MockData\" />
    <Folder Include="ViewModel\" />
    <Folder Include="wwwroot\assets\plugins\bootstrap-material-datetimepicker\css\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.8" />
  </ItemGroup>

</Project>
